### ISSUE TITLE
E2E Failures

### ISSUE THREAD

**Issue by ashcrow** [projectatomic/commissaire-http#62]
Our E2E tests are failing. We need to investigate and find out if the tests are starting to become out of date or if they are pointing to a bug we have in our code somewhere.

Example:
```
 Scenario: Retrieve existing host status with authentication  # features/hosts/retrieve.feature:65
    Given we have a valid username and password                # features/steps/__init__.py:39 0.000s
    And a host already exists at 192.168.152.110               # features/steps/hosts.py:37 0.001s
    And we have a cluster named honeynut                       # features/steps/cluster.py:29
Exception raised during method call:
Traceback (most recent call last):
  File "commissaire-service/src/commissaire_service/service/__init__.py", line 230, in on_message
    result = method(message=message, **body['params'])
  File "commissaire-service/src/commissaire_service/storage/__init__.py", line 170, in on_get
    full_model_instance = self._manager.get(model_instance)
  File "commissaire-service/src/commissaire_service/storage/storehandlermanager.py", line 198, in get
    handler = self._get_handler(model_instance)
  File "commissaire-service/src/commissaire_service/storage/storehandlermanager.py", line 150, in _get_handler
    handler_type, config, model_types = self._registry[type(model)]
KeyError: <class 'commissaire.models.Cluster'>

Message "7e256948-296d-45c7-b9a4-4c78993b275e" contains error: {'code': -32600, 'message': "<class 'commissaire.models.Cluster'>", 'data': {'exception': "<class 'KeyError'>"}}
Bus: Unable to get Cluster "honeynut": (-32600) <class 'commissaire.models.Cluster'>
Exception raised during method call:
Traceback (most recent call last):
  File "commissaire-service/src/commissaire_service/service/__init__.py", line 230, in on_message
    result = method(message=message, **body['params'])
  File "commissaire-service/src/commissaire_service/storage/__init__.py", line 150, in on_save
    saved_model_instance = self._manager.save(model_instance)
  File "commissaire-service/src/commissaire_service/storage/storehandlermanager.py", line 176, in save
    handler = self._get_handler(model_instance)
  File "commissaire-service/src/commissaire_service/storage/storehandlermanager.py", line 150, in _get_handler
    handler_type, config, model_types = self._registry[type(model)]
KeyError: <class 'commissaire.models.Cluster'>

Message "d070a7d9-2a5a-46db-9607-ad50a71a210c" contains error: {'code': -32600, 'message': "<class 'commissaire.models.Cluster'>", 'data': {'exception': "<class 'KeyError'>"}}
Bus: Unable to save Cluster "honeynut": (-32600) <class 'commissaire.models.Cluster'>
Exception raised while <function create_cluster at 0x7fe3c3a05510> handled "{'id': '3708cb25-d617-4a69-85b5-bcbaa44e26bc', 'method': 'PUT', 'params': {'_': '', 'name': 'honeynut'}, 'jsonrpc': '2.0'}":
Traceback (most recent call last):
  File "commissaire-http/src/commissaire_http/dispatcher/__init__.py", line 251, in dispatch
    result = handler(jsonrpc_msg, bus=self._bus)
  File "commissaire-http/src/commissaire_http/handlers/clusters/__init__.py", line 181, in create_cluster
    cluster = bus.storage.save(models.Cluster.new(**message['params']))
  File "commissaire/src/commissaire/storage/client.py", line 90, in save
    raise error
  File "commissaire/src/commissaire/storage/client.py", line 82, in save
    response = self.bus_mixin.request('storage.save', params=params)
  File "commissaire/src/commissaire/bus/__init__.py", line 174, in request
    raise RemoteProcedureCallError(message, code, data)
commissaire.bus.RemoteProcedureCallError: (-32600) <class 'commissaire.models.Cluster'>
```

**Comment by ashcrow** [comment]
See https://github.com/projectatomic/commissaire-http/pull/60

**Comment by ashcrow** [comment]
The E2E tests are running services without any configuration causing the storage service to have nothing to back it's data to. I'm looking to see what we can do to fix that.

**Comment by ashcrow** [comment]
I think I have a patch. Trying to test before my next fligh :sweat:

**Comment by ashcrow** [comment]
This works when running with the stand alone services though I have a feeling it will break when using vagrant. Next flight is boarding now... 

```diff
@@ -342,7 +345,10 @@ def before_all(context):
         if context.config.userdata.get('start-storage-service'):
             context.PROCESSES['commissaire-storage-service'] = try_start(
                 start_commissaire_service, 'commissaire-storage-service',
-                context, ['commissaire-storage-service'])
+                context, [
+                    'commissaire-storage-service',
+                    '--config-file',
+                    '../commissaire-service/conf/storage.conf'])
 
         if context.config.userdata.get('start-investigator-service'):
             context.PROCESSES['commissaire-investigator-service'] = try_start(
```

**Comment by mbarnes** [comment]
> This works when running with the stand alone services though I have a feeling it will break when using vagrant.

Ah, I've been using the vagrant environment exclusively.  The change should be safe wrt to vagrant because it only runs if `context.USE_VAGRANT` is `False`.

**Comment by mbarnes** [comment]
Working on this in https://github.com/projectatomic/commissaire/pull/90

I've got it down to 9 failures without Vagrant.  Some cases may need to be excluded.

**Comment by mbarnes** [comment]
This is fixed by https://github.com/projectatomic/commissaire/pull/90.
